# Generated by Django 4.2.5 on 2024-05-12 23:19

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, null=True, verbose_name='Activity')),
                ('pauses', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Pauses')),
                ('startTime', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='User')),
            ],
            options={
                'db_table': 'timers',
            },
        ),
    ]
