# Generated by Django 4.2.5 on 2024-05-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='activity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Activity'),
        ),
    ]
