# Generated by Django 4.2.5 on 2024-05-12 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP-address')),
                ('authDate', models.DateTimeField(auto_now_add=True, verbose_name='Auth date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='User')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-authDate'],
            },
        ),
    ]
