# Generated by Django 4.2.5 on 2024-05-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_activated_alter_user_registrationdate'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(verbose_name='Confirmation code')),
                ('sendingTime', models.DateTimeField(auto_now_add=True, verbose_name='Sending time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='User')),
            ],
            options={
                'db_table': 'email_confirmations',
            },
        ),
    ]
