# Generated by Django 4.2.5 on 2024-05-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Account activation status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration date'),
        ),
    ]
